### ISSUE TITLE
UnicodeDecodeError in apl.fix with Python 2.7

### ISSUE THREAD

**Issue by jayfoad** [marinuso/pynapl#2]
With Python 2.7.13 on Ubuntu 17.04:

```
>>> apl.fix("""
... :Namespace Test
... foo←42
... :EndNamespace
... """)
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "pynapl/APLPyConnect.py", line 389, in fix
    return self.eval("2⎕FIX ∆", *code)
  File "pynapl/APLPyConnect.py", line 409, in eval
    payload = APLArray.from_python([aplexpr, args], self.store).toJSONString()
  File "pynapl/Array.py", line 199, in from_python
    data=[APLArray.from_python(x,False,objectstore) for x in obj])
  File "pynapl/Array.py", line 199, in from_python
    data=[APLArray.from_python(x,False,objectstore) for x in obj])
  File "pynapl/Array.py", line 222, in from_python
    return APLArray.from_python(str(obj, "utf8"),False,objectstore)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 0: unexpected end of data
```

**Comment by marinuso** [comment]
This has now been fixed.
